name: iOS Screenshots

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    

jobs:
  screenshots:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install project dependecies
        run: flutter pub get

      - name: Build ios app
        run: flutter build ios --simulator --debug  

      - name: List available --simulator
        run: xcrun simctl list devices available
