name: iOS Screenshots

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --simulator --debug

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Boot iOS simulator
        run: |
          DEVICE_UDID="6F69910C-E4FA-488A-B9C2-41B770484810"

          echo "Using simulator: $DEVICE_UDID"
          echo "DEVICE_UDID=$DEVICE_UDID" >> "$GITHUB_ENV"

          xcrun simctl boot "$DEVICE_UDID" || true
          xcrun simctl bootstatus "$DEVICE_UDID" -b

      - name: Find app bundle identifier
        run: |
          APP_PATH="build/ios/iphonesimulator/Runner.app"

          BUNDLE_ID=$(
            /usr/libexec/PlistBuddy \
              -c "Print:CFBundleIdentifier" \
              "$APP_PATH/Info.plist"
          )

          echo "Bundle ID: $BUNDLE_ID"
          echo "BUNDLE_ID=$BUNDLE_ID" >> "$GITHUB_ENV"

      - name: Install app
        run: |
          echo "Installing app on simulator"

          xcrun simctl install \
          "$DEVICE_UDID" \
          build/ios/iphonesimulator/Runner.app

      - name: Launch app
        run: |
          echo "Launching app $BUNDLE_ID"

          xcrun simctl launch \
          "$DEVICE_UDID" \
          "BUNDLE_ID"
          sleep 5

      - name: Take screenshoot
        run: |
          mkdir -p screenshots
          echo " Taking screenshots"
          xcrun simctl io \
          "$DEVICE_UDID" \
          screenshoot \
          screenshots/home.png

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ios-screenshots
          path: screenshots/

