name: iOS Screenshots

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  screenshots:
    runs-on: macos-latest

    steps:
      # 1. Download the repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 3. Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build the Flutter app for the iOS Simulator
      - name: Build iOS app
        run: flutter build ios --simulator --debug

      # 5. Show the simulators available on the GitHub runner
      - name: List available simulators
        run: xcrun simctl list devices available

      # 6. Boot the simulator
      - name: Boot iOS Simulator
        run: |
          # iPhone 17 Pro running on iOS 26.5
          DEVICE_UDID="6EE862FE-93F2-4D55-946E-8745EE2B3A88"

          echo "Using simulator: $DEVICE_UDID"

          # Make DEVICE_UDID available to later steps
          echo "DEVICE_UDID=$DEVICE_UDID" >> "$GITHUB_ENV"

          # Boot the simulator
          xcrun simctl boot "$DEVICE_UDID" || true

          # Wait until the simulator has completely booted
          xcrun simctl bootstatus "$DEVICE_UDID" -b

      # 7. Install and launch the Flutter app
      - name: Install and launch app
        run: |
          echo "Installing app on simulator..."

          APP_PATH="build/ios/iphonesimulator/Runner.app"

          xcrun simctl install \
          "$DEVICE_UDID" \
          "$APP_PATH"

          BUNDLE_ID=$(
          /usr/libexec/PlistBuddy \
          -c "Print:CFBundleIdentifier" \
          "$APP_PATH/Info.plist"
          )

          echo "Bundle ID: $BUNDLE_ID"

          echo "Launching app..."

          xcrun simctl launch \
          "$DEVICE_UDID" \
          "$BUNDLE_ID"

          sleep 5
      # 8. Take a screenshot
      - name: Take screenshot
        run: |
          mkdir -p screenshots

          echo "Taking screenshot..."

          xcrun simctl io \
            "$DEVICE_UDID" \
            screenshot \
            screenshots/home.png

      # 9. Upload the screenshot as a GitHub Actions artifact
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ios-screenshots
          path: screenshots/
